// flightCostModel.ts — CANONICAL SINGLE SOURCE OF TRUTH for what one drone
// flight-hour costs. This file lives here, in the simulation repo, next to the
// physics that produces the flight hours. The marketing website consumes a
// byte-identical VENDORED COPY of this file (photonicinsecticides-website
// src/lib/flightCostModel.ts, regenerated by its scripts/sync-flight-cost.mjs).
// Edit here, never there.
//
// The pricing pipeline is deliberately two layers, each independently verifiable:
//   1. PHYSICS  (src/sim/engine.ts) turns pest pressure / a target grid into
//      flight HOURS. Cross-checked by the closed-form src/sim/hoppingModel.ts
//      (see scripts/verifyHopping.ts).
//   2. PRICING  (this file) turns flight hours into $/ha at stated unit costs.
//      scripts/costSweep.ts prices the simulated flight hours through this model,
//      so the published dataset — and therefore the website — is reproducible by
//      running the sweep in this one repo.
//
// Three deliberately distinct outputs (do NOT collapse them):
//   1. marginalFlightCostPerHour        — costs that exist BECAUSE the drone flies:
//        battery cycle depreciation + charging electricity + flight-dependent wear.
//   2. ordinaryDroneCostPerHour         — marginal + capital ALLOCATION of the
//        airframe/electronics and shared charger. Capital allocation is an
//        accounting spread of purchase price over expected utilisation, not
//        physical per-hour wear.
//   3. fullyAllocatedSystemCostPerHour  — ordinary + the specialised optical/laser
//        payload, kept visible as its own line so reviewers can separate ordinary
//        drone economics from the pest-control equipment.
//
// Units used internally throughout: EUR, W, Wh, kWh, hours, years, efficiencies
// as decimal fractions (0..1). The site treats USD ≈ EUR at this scale (documented
// on the cart comparison); the sim dataset is USD-denominated.
//
// Calibration note (defaults): the "site baseline" scenario reproduces the
// laser_drone_sim cost model exactly (sim/defaults.ts: battery 140 Wh · 400
// cycles · €180, charger eff 0.9, electricity €0.15/kWh, maintenance €1/h,
// airframe €1,800 over 1,500 flight-h, laser €6,000 over 10,000 flight-h).
// averagePowerW = 253 W is the sweep dataset's mission-average electrical power
// for the 2.2 kg drone (reverse-derived: dataset battery $/ha ÷ flight-h matches
// €180×253/(140×400) = €0.813/h to <1%). The physics stays in the sim — this
// module only prices its flight hours.

export interface DroneFlightCostInputs {
  // battery
  batteryPriceEur: number;        // € per pack
  batteryCapacityWh: number;      // usable Wh per full cycle
  batteryCycleLife: number;       // full-equivalent cycles until replacement
  averagePowerW: number;          // mean electrical draw while operating, W
  chargingEfficiency: number;     // 0..1 — wall-to-battery
  // energy
  electricityPricePerKwh: number; // €/kWh at the wall
  // flight-dependent maintenance
  propellerPerHour: number;       // €/flight-h — props & minor parts
  motorBearingPerHour: number;    // €/flight-h — motors & bearings
  additionalMaintenancePerHour: number; // €/flight-h — optional extra allowance
  // drone capital (airframe + electronics, excl. batteries)
  dronePurchasePriceEur: number;
  droneWriteOffYears: number;
  droneOperatingHoursPerYear: number;
  droneResidualValueEur: number;
  /** Years the airframe physically OUTLIVES its accounting write-off. A flight hour
   * doesn't consume the airframe — so if it lasts beyond the write-off period, the
   * one-time cost spreads over the longer real life and the per-hour capital drops
   * (toward the marginal rate once fully paid off). 0 = dies at write-off. */
  droneOutliveWriteOffYears: number;
  // shared equipment (controller + charger, split across a fleet)
  chargerPurchasePriceEur: number;
  chargerWriteOffYears: number;
  chargerSharedDrones: number;          // drones sharing one controller/charger
  chargerAnnualHoursPerDrone: number;   // utilisation of each sharing drone, h/yr
  // optical / laser payload (allocated per flight hour, as the sim already does)
  opticalPurchasePriceEur: number;
  opticalLifetimeHours: number;
  opticalResidualValueEur: number;
}

export interface DroneFlightCostResult {
  // intermediates (exposed so the UI can show substituted formulas)
  batteryLifetimeEnergyWh: number;   // capacity × cycles
  energyPerFlightHourWh: number;     // averagePowerW × 1 h
  gridEnergyPerHourKwh: number;      // power / efficiency / 1000
  droneDepreciableValueEur: number;  // purchase − residual
  droneLifetimeHours: number;        // writeOffYears × hours/yr
  // per-hour components
  batteryDepreciationPerHour: number;
  electricityCostPerHour: number;
  maintenanceCostPerHour: number;
  droneCapitalCostPerHour: number;
  sharedEquipmentCostPerHour: number;
  opticalCapitalCostPerHour: number;
  // the three headline outputs
  marginalFlightCostPerHour: number;
  ordinaryDroneCostPerHour: number;
  fullyAllocatedSystemCostPerHour: number;
  /** human-readable validation problems; when non-empty the affected components are 0 */
  errors: string[];
}

const bad = (n: number) => !Number.isFinite(n) || Number.isNaN(n);

export function calculateDroneFlightHourCost(i: DroneFlightCostInputs): DroneFlightCostResult {
  const errors: string[] = [];
  const check = (cond: boolean, msg: string) => { if (cond) errors.push(msg); return cond; };

  // ---- validation (each failure zeroes only its own component, visibly) ----
  const numsOk = !check(Object.values(i).some((v) => typeof v !== "number" || bad(v)),
    "One or more inputs are not valid numbers.");
  const negOk = !check(numsOk && Object.values(i).some((v) => v < 0),
    "Costs, capacities and periods cannot be negative.");
  const ok = numsOk && negOk;

  const battOk = ok && !check(i.batteryCapacityWh <= 0 || i.batteryCycleLife <= 0,
    "Battery capacity and cycle life must be greater than zero.");
  const effOk = ok && !check(i.chargingEfficiency <= 0 || i.chargingEfficiency > 1,
    "Charging efficiency must be between 0 and 1 (e.g. 0.9 = 90%).");
  const droneUtilOk = ok && !check(i.droneWriteOffYears <= 0 || i.droneOperatingHoursPerYear <= 0,
    "Drone write-off period and operating hours per year must be greater than zero.");
  const droneResOk = ok && !check(i.droneResidualValueEur > i.dronePurchasePriceEur,
    "Drone residual value cannot exceed its purchase price.");
  const chargerOk = ok && (i.chargerPurchasePriceEur === 0 ||
    !check(i.chargerWriteOffYears <= 0 || i.chargerSharedDrones <= 0 || i.chargerAnnualHoursPerDrone <= 0,
      "Charger write-off period, shared-drone count and annual utilisation must be greater than zero."));
  const optOk = ok && (i.opticalPurchasePriceEur === 0 ||
    (!check(i.opticalLifetimeHours <= 0, "Optical-system lifetime hours must be greater than zero.") &&
     !check(i.opticalResidualValueEur > i.opticalPurchasePriceEur,
       "Optical residual value cannot exceed its purchase price.")));

  // ---- battery: € × Wh-used / lifetime-Wh ----
  const batteryLifetimeEnergyWh = battOk ? i.batteryCapacityWh * i.batteryCycleLife : 0;
  const energyPerFlightHourWh = ok ? i.averagePowerW * 1 : 0;
  const batteryDepreciationPerHour = battOk
    ? (i.batteryPriceEur * energyPerFlightHourWh) / batteryLifetimeEnergyWh : 0;

  // ---- electricity: wall energy incl. charging losses ----
  const gridEnergyPerHourKwh = effOk ? i.averagePowerW / i.chargingEfficiency / 1000 : 0;
  const electricityCostPerHour = effOk ? gridEnergyPerHourKwh * i.electricityPricePerKwh : 0;

  // ---- flight-dependent maintenance ----
  const maintenanceCostPerHour = ok
    ? i.propellerPerHour + i.motorBearingPerHour + i.additionalMaintenancePerHour : 0;

  // ---- drone capital: (price − residual) / (years × h/yr) — allocation, not wear ----
  const droneDepreciableValueEur = droneResOk ? Math.max(i.dronePurchasePriceEur - i.droneResidualValueEur, 0) : 0;
  // Amortize the one-time airframe over its REAL physical life = write-off period plus
  // any years it outlives that write-off. A durable drone spreads its cost over more
  // hours ⇒ lower €/flight-hour ⇒ lower €/ha.
  const droneRealLifeYears = i.droneWriteOffYears + Math.max(i.droneOutliveWriteOffYears, 0);
  const droneLifetimeHours = droneUtilOk ? droneRealLifeYears * i.droneOperatingHoursPerYear : 0;
  const droneCapitalCostPerHour = droneUtilOk && droneResOk && droneLifetimeHours > 0
    ? droneDepreciableValueEur / droneLifetimeHours : 0;

  // ---- shared charger/controller: (price / write-off yrs) / (drones × h/yr each) ----
  const sharedEquipmentCostPerHour = chargerOk && i.chargerPurchasePriceEur > 0
    ? (i.chargerPurchasePriceEur / i.chargerWriteOffYears) /
      (i.chargerSharedDrones * i.chargerAnnualHoursPerDrone)
    : 0;

  // ---- optical/laser payload: (price − residual) / lifetime flight-hours ----
  const opticalCapitalCostPerHour = optOk && i.opticalPurchasePriceEur > 0
    ? Math.max(i.opticalPurchasePriceEur - i.opticalResidualValueEur, 0) / i.opticalLifetimeHours
    : 0;

  const marginalFlightCostPerHour = batteryDepreciationPerHour + electricityCostPerHour + maintenanceCostPerHour;
  const ordinaryDroneCostPerHour = marginalFlightCostPerHour + droneCapitalCostPerHour + sharedEquipmentCostPerHour;
  const fullyAllocatedSystemCostPerHour = ordinaryDroneCostPerHour + opticalCapitalCostPerHour;

  return {
    batteryLifetimeEnergyWh, energyPerFlightHourWh, gridEnergyPerHourKwh,
    droneDepreciableValueEur, droneLifetimeHours,
    batteryDepreciationPerHour, electricityCostPerHour, maintenanceCostPerHour,
    droneCapitalCostPerHour, sharedEquipmentCostPerHour, opticalCapitalCostPerHour,
    marginalFlightCostPerHour, ordinaryDroneCostPerHour, fullyAllocatedSystemCostPerHour,
    errors,
  };
}

// ---------------------------------------------------------------------------
// Scenarios. "site-baseline" reproduces the published sim cost model exactly and
// is the default everywhere; the others are plausible, documented variations —
// not straw men. Any manual edit becomes "custom".
// ---------------------------------------------------------------------------

export type FlightCostScenarioId = "site-baseline" | "paper-small-drone" | "conservative" | "custom";

/** Sim-calibrated mature-operation baseline (laser_drone_sim sim/defaults.ts). */
export const FLIGHT_COST_DEFAULTS: DroneFlightCostInputs = {
  batteryPriceEur: 180,
  batteryCapacityWh: 140,
  batteryCycleLife: 400,
  averagePowerW: 253,          // sweep-dataset mission average, 2.2 kg all-up
  chargingEfficiency: 0.9,
  electricityPricePerKwh: 0.15,
  // €1/h total, matching the sim's maintenanceCostPerFlightHourUsd; the 50/30/20
  // split across parts is presentational only.
  propellerPerHour: 0.5,
  motorBearingPerHour: 0.3,
  additionalMaintenancePerHour: 0.2,
  dronePurchasePriceEur: 1800,
  droneWriteOffYears: 5,       // 5 yr × 300 h/yr = the sim's 1,500 flight-h life
  droneOperatingHoursPerYear: 300,
  droneResidualValueEur: 0,
  droneOutliveWriteOffYears: 0, // conservative: airframe dies at write-off (no bonus life)
  chargerPurchasePriceEur: 0,  // the published sim cost model has no charger capex;
  chargerWriteOffYears: 5,     // set a price > 0 to include one
  chargerSharedDrones: 5,
  chargerAnnualHoursPerDrone: 300,
  opticalPurchasePriceEur: 6000,
  opticalLifetimeHours: 10000,
  opticalResidualValueEur: 0,
};

export const FLIGHT_COST_SCENARIOS: Record<Exclude<FlightCostScenarioId, "custom">, {
  name: string; note: string; inputs: DroneFlightCostInputs;
}> = {
  "site-baseline": {
    name: "Mature operation (site baseline)",
    note: "Sim-calibrated: reproduces the published cost sweep exactly. 2.2 kg drone, 253 W mission average.",
    inputs: FLIGHT_COST_DEFAULTS,
  },
  "paper-small-drone": {
    name: "Paper's 0.5 kg drone (optimistic)",
    note: "The paper's small-drone assumptions: 17.3 Wh pack, 90 W hop power, 1,000 cycles. NB: the cost chart's flight hours are simulated for the 2.2 kg drone, so applying these rates there is an approximation.",
    inputs: {
      ...FLIGHT_COST_DEFAULTS,
      batteryPriceEur: 50, batteryCapacityWh: 17.3, batteryCycleLife: 1000,
      averagePowerW: 90, chargingEfficiency: 0.85, electricityPricePerKwh: 0.30,
      propellerPerHour: 0.03, motorBearingPerHour: 0.02, additionalMaintenancePerHour: 0,
      dronePurchasePriceEur: 1500,
    },
  },
  conservative: {
    name: "Early deployment (conservative)",
    note: "First-fleet economics: pricier short-lived batteries, dearer power, more maintenance, shorter write-off, charger included.",
    inputs: {
      ...FLIGHT_COST_DEFAULTS,
      batteryPriceEur: 250, batteryCycleLife: 300,
      chargingEfficiency: 0.85, electricityPricePerKwh: 0.40,
      propellerPerHour: 1.0, motorBearingPerHour: 0.6, additionalMaintenancePerHour: 0.4,
      dronePurchasePriceEur: 3000, droneWriteOffYears: 3, droneOperatingHoursPerYear: 200,
      chargerPurchasePriceEur: 300, chargerSharedDrones: 3, chargerAnnualHoursPerDrone: 200,
      opticalPurchasePriceEur: 8000, opticalLifetimeHours: 5000,
    },
  },
};

// ---------------------------------------------------------------------------
// Derived rate bundles for the dependent simulations. Each sim picks the
// economically appropriate output — do NOT feed every sim the same total.
// ---------------------------------------------------------------------------

/** Rates for a SCOUT drone: camera payload, no laser → marginal + drone capital
 * + shared charger, EXCLUDING the optical allocation. */
export function scoutCostPerFlightHour(r: DroneFlightCostResult): number {
  return r.ordinaryDroneCostPerHour;
}

/** Rates for the SHOOTING drone (carries the laser) → fully allocated. */
export function shootingCostPerFlightHour(r: DroneFlightCostResult): number {
  return r.fullyAllocatedSystemCostPerHour;
}

/** Price a simulated mission: the sweep dataset supplies the PHYSICS (flight hours
 * per sweep over `fieldHa`); this shared model supplies the ECONOMICS. Component
 * split mirrors the cost chart's checkboxes: "amortization" = capital allocations
 * (drone + charger + laser) + flight-dependent maintenance; battery and
 * electricity are separate. All €/ha for ONE sweep. */
export function priceFlightHoursPerHa(flightHours: number, fieldHa: number, r: DroneFlightCostResult) {
  const ha = Math.max(fieldHa, 1e-9);
  return {
    amortization: (flightHours * (r.droneCapitalCostPerHour + r.sharedEquipmentCostPerHour +
      r.opticalCapitalCostPerHour + r.maintenanceCostPerHour)) / ha,
    battery: (flightHours * r.batteryDepreciationPerHour) / ha,
    electricity: (flightHours * r.electricityCostPerHour) / ha,
  };
}
